name: Build

on:
  workflow_call:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Ejecutar build
        run: |
          echo "Compilando aplicación..."